# Generated by Django 5.2.7 on 2025-10-05 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Movie title', max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the movie in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('description', models.TextField(blank=True, help_text='Movie description')),
                ('genre', models.CharField(blank=True, help_text='Movie genre', max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Movie rating out of 10', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('release_date', models.DateField(blank=True, help_text='Movie release date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(help_text='Screen/Theater name', max_length=100)),
                ('date_time', models.DateTimeField(help_text='Show date and time')),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats available', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(help_text='Movie being shown', on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(help_text='Seat number (1-based indexing)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', help_text='Booking status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(help_text='Show for which booking is made', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.show')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('show', 'seat_number')},
            },
        ),
    ]
